sudo: false
dist: trusty

language: go

cache:
  yarn: true
  directories:
  - node_modules

env:
- NODE_VERSION="8.11.3"

before_install:
- env
- nvm install $NODE_VERSION
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH=$HOME/.yarn/bin:$PATH

before_script: yarn install

# TODO add tests
script:
- npm run build
- npm run buildgo

before_deploy:
- cp -r . /tmp/consul-datasource
- cd /tmp
- rm -rf ./consul-datasource/vendor
- rm -rf ./consul-datasource/node_modules
- rm -rf ./consul-datasource/.git
- rm -rf ./consul-datasource/.idea
- rm -rf ./consul-datasource/*.iml
- zip -r consul-datasource.zip consul-datasource-0.0.2


deploy:
- provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file: /tmp/consul-datasource.zip
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
