sudo: false
dist: trusty

language: go

cache:
  yarn: true
  directories:
  - node_modules

env:
- NODE_VERSION="8.11.3"

before_install:
- env
- nvm install $NODE_VERSION
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH=$HOME/.yarn/bin:$PATH

before_script: yarn install

# TODO add tests
script:
- npm run build
- npm run buildgo
- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- cp -r . /tmp/consul-datasource-${TRAVIS_TAG}
- cd /tmp
- rm -rf ./consul-datasource-${TRAVIS_TAG}/vendor
- rm -rf ./consul-datasource-${TRAVIS_TAG}/node_modules
- rm -rf ./consul-datasource-${TRAVIS_TAG}/.git
- rm -rf ./consul-datasource-${TRAVIS_TAG}/.idea
- rm -rf ./consul-datasource-${TRAVIS_TAG}/*.iml
- zip -r consul-datasource-${TRAVIS_TAG}.zip consul-datasource-${TRAVIS_TAG}


deploy:
- provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file: /tmp/consul-datasource-${TRAVIS_TAG}.zip
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
